// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: myserver/protofiles/init.proto

package protofiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InitConnectionClient is the client API for InitConnection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitConnectionClient interface {
	SendOTP(ctx context.Context, in *OTP, opts ...grpc.CallOption) (*OTP, error)
}

type initConnectionClient struct {
	cc grpc.ClientConnInterface
}

func NewInitConnectionClient(cc grpc.ClientConnInterface) InitConnectionClient {
	return &initConnectionClient{cc}
}

func (c *initConnectionClient) SendOTP(ctx context.Context, in *OTP, opts ...grpc.CallOption) (*OTP, error) {
	out := new(OTP)
	err := c.cc.Invoke(ctx, "/InitConnection/SendOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitConnectionServer is the server API for InitConnection service.
// All implementations must embed UnimplementedInitConnectionServer
// for forward compatibility
type InitConnectionServer interface {
	SendOTP(context.Context, *OTP) (*OTP, error)
	mustEmbedUnimplementedInitConnectionServer()
}

// UnimplementedInitConnectionServer must be embedded to have forward compatible implementations.
type UnimplementedInitConnectionServer struct {
}

func (UnimplementedInitConnectionServer) SendOTP(context.Context, *OTP) (*OTP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTP not implemented")
}
func (UnimplementedInitConnectionServer) mustEmbedUnimplementedInitConnectionServer() {}

// UnsafeInitConnectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitConnectionServer will
// result in compilation errors.
type UnsafeInitConnectionServer interface {
	mustEmbedUnimplementedInitConnectionServer()
}

func RegisterInitConnectionServer(s grpc.ServiceRegistrar, srv InitConnectionServer) {
	s.RegisterService(&InitConnection_ServiceDesc, srv)
}

func _InitConnection_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitConnectionServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InitConnection/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitConnectionServer).SendOTP(ctx, req.(*OTP))
	}
	return interceptor(ctx, in, info, handler)
}

// InitConnection_ServiceDesc is the grpc.ServiceDesc for InitConnection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitConnection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InitConnection",
	HandlerType: (*InitConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOTP",
			Handler:    _InitConnection_SendOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myserver/protofiles/init.proto",
}
